# =======================================
# PARAMETERS FOR SIMULATION

N_QUBITS = 4
N_LAYERS = 4
N_BITS   = N_QUBITS * N_LAYERS * 5

SEED = 50
N_TRIALS = 100

N_LANDMARKS = 20
N_EPOCH = 30
N_POPSIZE = 20
N_PM = 0.1