"""
Engineered ("quantum-native") dataset generator.

Implements the data-generation recipe used to demonstrate a quantum
advantage on data (Huang et al., "Power of data in quantum machine
learning", Nat. Commun. 2021): instead of labelling real-world points,
labels are produced by a genuinely quantum process —

    |x_i>            = U_enc(x_i) |0>^n
    y_i (continuous) = <x_i| U_QNN^dagger  O  U_QNN |x_i>
    y_i (binary)      = sign(y_i - threshold)

U_enc is a random data-encoding circuit (angles scaled by the features,
exactly like `build_circuit`). U_QNN is a *second*, independent random
circuit with its own frozen parameters (data-independent, built with
`build_circuit_params`) standing in for the trained QNN in the paper.
O is a random Hermitian observable (weighted sum of single-qubit Z's).

Both U_enc and U_QNN are sampled once and then frozen, so f(x) is an
arbitrary, fixed function of x in Hilbert space. A quantum kernel built
from U_enc can represent it well; nothing guarantees it is smooth,
low-degree, or otherwise easy for a classical model working only with
the raw feature vector x, which is exactly the point of the construction.

This module only builds the (X, y) arrays and freezes the generating
circuits/observable for reference — it plugs directly into the existing
`preprocess`, `classical_baseline`, and Optuna/Mealpy pipeline in this
repo, since X already comes out in the [-1, 1] range on N_QUBITS features.
"""

import numpy as np
import pennylane as qml

from ..circuit.candidates import OptunaCandidate
from ..circuit.building import build_circuit, build_circuit_params

GATE_POOL = ("H", "CNOT", "RX", "RY", "RZ", "I")


def _random_candidate(
    n_qubits: int, n_layers: int, rng: np.random.Generator,
    gate_pool: tuple = GATE_POOL,
) -> OptunaCandidate:
    """Samples a random fixed circuit structure + angles as an OptunaCandidate."""
    gates = list(rng.choice(gate_pool, size=n_qubits * n_layers))
    angles = list(rng.uniform(0, 2 * np.pi, size=n_qubits * n_layers))
    return OptunaCandidate(n_qubits, n_layers, gates, angles)


def _random_observable(n_qubits: int, rng: np.random.Generator) -> qml.Hamiltonian:
    """Random weighted sum of single-qubit Z's -> Hermitian observable, ||O||<=1-ish."""
    weights = rng.uniform(-1, 1, size=n_qubits)
    weights = weights / np.sum(np.abs(weights))  # keep y in a bounded, comparable range
    return qml.Hamiltonian(list(weights), [qml.PauliZ(q) for q in range(n_qubits)])


def generate_synthetic_dataset(
    n_samples: int,
    n_qubits: int,
    n_layers_enc: int = 4,
    n_layers_qnn: int = 4,
    seed: int = 0,
    gate_pool: tuple = GATE_POOL,
) -> dict:
    """
    Builds a supervised dataset whose labels are generated by a frozen,
    random quantum process (encoding circuit -> random QNN -> observable).

    Args:
        n_samples:    Number of data points to generate.
        n_qubits:     Feature dimension / number of qubits.
        n_layers_enc: Depth of the (frozen, random) data-encoding circuit U_enc.
        n_layers_qnn: Depth of the (frozen, random) label-generating circuit U_QNN.
        seed:         Seed controlling both the generating circuits/observable
                      and the sampled X, for full reproducibility.
        gate_pool:    Gate alphabet to sample from (matches the repo's search space).

    Returns:
        dict with:
            X            (n_samples, n_qubits) in [-1, 1], ready for `preprocess`-free use
            y_continuous (n_samples,) raw expectation values <x|U_QNN^+ O U_QNN|x>
            y_binary     (n_samples,) in {-1, +1}, split at the median of y_continuous
            enc_candidate, qnn_candidate, qnn_theta, observable: the frozen generators,
                          kept for reproducibility / inspection (e.g. drawing the circuit
                          that "planted" the labels).
    """
    rng = np.random.default_rng(seed)

    # Frozen, random data-encoding circuit U_enc(x) — reuses the repo's own
    # gate alphabet, so a matching quantum kernel search can plausibly recover it.
    enc_candidate = _random_candidate(n_qubits, n_layers_enc, rng, gate_pool)

    # Frozen, random "trained QNN" U_QNN — data independent, fixed parameters.
    qnn_gates = list(rng.choice(gate_pool, size=n_qubits * n_layers_qnn))
    qnn_candidate = OptunaCandidate(n_qubits, n_layers_qnn, qnn_gates, [0.0] * len(qnn_gates))
    qnn_theta = rng.uniform(0, 2 * np.pi, size=n_qubits * n_layers_qnn)

    # Frozen random observable O.
    observable = _random_observable(n_qubits, rng)

    # Random classical inputs, in the same [-1, 1] convention the rest of the
    # pipeline expects after MinMaxScaler.
    X = rng.uniform(-1, 1, size=(n_samples, n_qubits))

    dev = qml.device("default.qubit", wires=n_qubits)

    @qml.qnode(dev)
    def label_circuit(x):
        build_circuit(enc_candidate, x)                    # U_enc(x)
        build_circuit_params(qnn_candidate, qnn_theta)      # U_QNN  (fixed, data-independent)
        return qml.expval(observable)                       # <x| U_QNN^+ O U_QNN |x>

    y_continuous = np.array([float(label_circuit(x)) for x in X])

    # Binarize at the median -> balanced classes by construction.
    threshold = np.median(y_continuous)
    y_binary = np.where(y_continuous >= threshold, 1, -1)

    return {
        "X": X,
        "y_continuous": y_continuous,
        "y_binary": y_binary,
        "enc_candidate": enc_candidate,
        "qnn_candidate": qnn_candidate,
        "qnn_theta": qnn_theta,
        "observable": observable,
        "threshold": threshold,
    }


def train_test_split_synthetic(
    data: dict, test_size: float = 0.3, seed: int = 42,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Splits the output of `generate_synthetic_dataset` into train/test sets.
    No PCA/scaling is applied since X is already generated directly on
    n_qubits features in [-1, 1] — unlike `preprocess`, which additionally
    reduces real-world data down to n_qubits dimensions.
    """
    from sklearn.model_selection import train_test_split

    return train_test_split(
        data["X"], data["y_binary"],
        test_size=test_size, random_state=seed, stratify=data["y_binary"],
    )